[package]
name = "slugcat-race-tests"
version = "1.0.0"
edition = "2021"

[dependencies]
raylib = "5.0.2"
rayon = "1.10.0"
rand = "0.9.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
